FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY tasks.py .

EXPOSE 5555

CMD ["celery", "-A", "tasks", "flower", \
     "--port=5555", \
     "--address=0.0.0.0"]